using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//まノUnity UI{Αw
using UnityEngine.UI;

public class BGM : MonoBehaviour
{
    [Header("北瞽刀q")]
    public Slider AudioSilder;
    //public AudioSource BGM_Audio;
    // Start is called before the first frame update
    void Start()
    {
        AudioListener.pause = false;
        Static.SaveAudiovolueme = 0.6f;
        //Xи汤xs杭骗权AudioSlider
        //X AudioSlider = 办跑计把计
        AudioSilder.value = Static.SaveAudiovolueme;
    }
    
    // Update is called once per frame
    void Update()
    {
           //AudioListener.volume 刀q计痊嫂0f-1f
           //Slider杭骗=0f-1f
           //俱砰n淡刀q=Slider秸俱杭骗
        AudioListener.volume = AudioSilder.value;
        //X AudioSlider = 办跑计把计
        Static.SaveAudiovolueme = AudioSilder.value;
    }
    public void ControlBGM(bool Control)
    {
        if (Control)
            //BGM_Audio.Play();
            AudioListener.pause = false;
        else
            AudioListener.pause = true;
            //BGM_Audio.Stop();
    }
}